import express from 'express';
import { fileURLToPath } from 'node:url';

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const badge = status => `<span class="badge">${esc(status)}</span>`;
const toolLink = tool => `/tools/${encodeURIComponent(tool.slug)}`;
const card = (tool, index) => `<article class="tool-row" data-tool data-title="${esc(`${tool.title} ${tool.description}`.toLowerCase())}" data-input="${esc(tool.inputType)}" data-output="${esc(tool.outputType)}" data-category="${esc(tool.category)}" data-status="${esc(tool.status)}" data-price="${esc(tool.price.label)}"><span class="index">0${index + 1}</span><div><div class="row-heading"><h3><a href="${toolLink(tool)}">${esc(tool.title)}</a></h3>${badge(tool.status)}</div><p>${esc(tool.description)}</p><span class="meta">${esc(tool.inputType)} → ${esc(tool.outputType)} · ${esc(tool.price.label)}</span></div><a class="arrow" aria-label="Explore ${esc(tool.title)}" href="${toolLink(tool)}">↗</a></article>`;
const page = (title, content, path) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Task-focused workspaces with clear inputs, transparent prices and private results. Explore the AV Hub local preview."><title>${esc(title)} · AV Hub</title><link rel="stylesheet" href="/human.css"><script defer src="/human.js"></script></head><body data-page="${esc(path)}"><a class="skip" href="#main">Skip to content</a><div class="preview-strip">LOCAL PREVIEW <span>Thoughtfully built. Still taking shape.</span> <a href="/help">What works today ↗</a></div><header><a class="brand" href="/" aria-label="AV Hub home"><span class="brand-mark">av</span><span>AV HUB<small>Useful by design.</small></span></a><nav aria-label="Main navigation"><a href="/tools" ${path.startsWith('/tools') ? 'aria-current="page"' : ''}>Tools</a><a href="/pricing" ${path === '/pricing' ? 'aria-current="page"' : ''}>Pricing</a><a href="/developers" ${path === '/developers' ? 'aria-current="page"' : ''}>Developers</a></nav><a class="account-link" href="/account/jobs">Your workspace <span>↗</span></a></header><main id="main">${content}</main><footer><a class="brand" href="/">AV HUB</a><p>Small tasks. Considered tools.</p><nav aria-label="Footer"><a href="/help">Help</a><a href="/legal/privacy">Privacy · draft</a><a href="/legal/terms">Terms · draft</a></nav><small>Local preview. No purchases or live payments.</small></footer></body></html>`;
const intro = (eyebrow, title, text) => `<section class="page-intro"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></section>`;

export function createHumanPages({ service }) {
  const router = express.Router();
  router.get('/human.css', (_req, res) => res.sendFile(fileURLToPath(new URL('../public/human.css', import.meta.url))));
  router.get('/human.js', (_req, res) => res.sendFile(fileURLToPath(new URL('../public/human.js', import.meta.url))));
  const tools = () => { const catalog = service.catalog(); return [...catalog.ready, ...catalog.previews]; };
  const send = (req, res, title, body) => res.set('Content-Security-Policy', "default-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'").type('html').send(page(title, body, req.path));
  router.get('/', (req, res) => {
    const entries = tools(); const first = entries.find(tool => tool.status === 'Preview');
    send(req, res, 'Small tasks, clearer outcomes', `<section class="hero"><div><p class="eyebrow"><span class="dot"></span> A MORE CONSIDERED WAY TO WORK</p><h1>Small tasks.<br>Clearer <em>outcomes.</em></h1><p class="lead">Useful tools for people.<br>Callable capabilities for agents.</p><p class="hero-copy">Find the right workspace, know the cost, and move from a small task to a useful result. Start with our honest local preview.</p><div class="actions"><a class="button" href="/tools">Explore the tools <span>↗</span></a>${first ? `<a class="text-link" href="${toolLink(first)}">Try the text preview →</a>` : ''}</div><p class="fine">No wallet required. No real money in this preview.</p></div><aside class="specimen"><div class="specimen-top">THE WORKSPACE, IN MINIATURE ${badge('Sample')}</div><p class="specimen-label">01 / YOUR INPUT</p><blockquote>“A clearer way to get the small things done.”</blockquote><div class="flow-line"><span>Text</span><span>↓</span><span>Local processing</span></div><p class="specimen-label">02 / A CLEAR RESULT</p><div class="result-numbers"><div><strong>9</strong><span>words</span></div><div><strong>43</strong><span>characters</span></div><span class="result-check">✓</span></div><p class="fine">Illustrative sample · counts and excerpt only.<br>No AI analysis or rewriting.</p></aside></section><section class="section"><div class="section-heading"><div><p class="eyebrow">A SMALL, HONEST START</p><h2>Find your starting point.</h2></div><a class="text-link" href="/tools">View the catalog ↗</a></div><p class="section-note">One working local sample and two future workspace concepts. Commercial tools are still being validated.</p>${entries.slice(0, 3).map(card).join('')}</section><section class="principles"><div><span class="index">01 / DISCOVER</span><h3>A task, not a maze.</h3><p>Start with what you need to do. See inputs, outputs and limitations before you begin.</p></div><div><span class="index">02 / REVIEW</span><h3>The cost comes first.</h3><p>Review an exact server quote before each run. This preview uses demo credits only.</p></div><div><span class="index">03 / KEEP</span><h3>Your result, in reach.</h3><p>See your sample result and download it privately within your local session.</p></div></section><section class="developer-callout"><p class="eyebrow">FOR THE PEOPLE BUILDING WHAT’S NEXT</p><h2>One capability.<br>More ways to use it.</h2><div><p>The same registry supports browser workspaces and developer integrations. Explore the HTTP and agent interface.</p><a class="text-link" href="/developers">Open the developer guide ↗</a></div></section>`);
  });
  router.get('/tools', (req, res, next) => {
    if (req.query.format === 'json' || !req.get('accept')?.includes('text/html') || req.get('accept')?.includes('application/json')) return next();
    const entries = tools();
    const filter = (name, label, values) => `<label>${label}<select data-filter="${name}"><option value="">All ${label.toLowerCase()}</option>${[...new Set(values)].map(value => `<option>${esc(value)}</option>`).join('')}</select></label>`;
    send(req, res, 'Tools', `${intro('THE TOOL CATALOG', 'A place to begin.', 'Find a workspace that fits your task. Every listing tells you what it accepts, what it returns, and where it stands.')}<section class="catalog"><form class="filters" role="search"><label class="search">Search tools<input type="search" id="tool-search" placeholder="What would you like to work on?"></label>${filter('input', 'Input', entries.map(tool => tool.inputType))}${filter('output', 'Output', entries.map(tool => tool.outputType))}${filter('status', 'Availability', entries.map(tool => tool.status))}${filter('category', 'Category', entries.map(tool => tool.category))}${filter('price', 'Price', entries.map(tool => tool.price.label))}</form><p class="section-note" id="catalog-count" aria-live="polite">${entries.length} workspaces · local preview catalog</p>${entries.map(card).join('')}<div id="catalog-empty" class="empty" hidden><h3>No tools match those filters.</h3><p>Try a broader search or clear the filters.</p><button type="button" id="clear-filters" class="button secondary">Clear filters</button></div></section>`);
  });
  router.get('/tools/:slug', (req, res, next) => {
    const tool = tools().find(entry => entry.slug === req.params.slug); if (!tool) return next();
    const runnable = tool.source === 'preview' && tool.status === 'Preview';
    send(req, res, tool.title, `<section class="tool-intro"><a class="text-link" href="/tools">← All tools</a><div class="title-line"><h1>${esc(tool.title)}</h1>${badge(tool.status)}</div><p class="lead">${esc(tool.description)}</p><p class="meta">${esc(tool.inputType)} → ${esc(tool.outputType)} · Version ${esc(tool.version)} · ${esc(tool.price.label)}</p></section><section class="workspace-grid"><div class="workspace"><p class="eyebrow">01 / YOUR INPUT</p>${runnable ? `<form id="workspace-form" data-capability="${esc(tool.id)}"><label for="workspace-text">Your text</label><textarea id="workspace-text" name="text" required maxlength="4000" rows="8" placeholder="Paste a small piece of text to try the workflow…"></textarea><div class="input-meta"><button class="text-link" id="use-example" type="button" data-example="${esc(tool.exampleInput.text)}">Use sample text</button><span id="character-count">0 / 4,000</span></div><p class="fine">Local sample only. Do not enter confidential data.</p><button class="button" type="submit" id="quote-button">Review demo quote →</button></form><section id="quote-panel" class="quote-panel" hidden><p class="eyebrow">02 / REVIEW YOUR QUOTE ${badge('Demo')}</p><p id="quote-detail"></p><label class="confirm"><input type="checkbox" id="quote-confirm"> I confirm this demo quote. No real payment is involved.</label><button class="button" id="run-button" type="button" disabled>Run local sample →</button></section>` : `<div class="empty"><h2>This workspace is ${esc(tool.status.toLowerCase())}.</h2><p>${runnable ? '' : 'Execution is not enabled. Explore the supported text preview to try the input-to-result flow.'}</p><a class="button secondary" href="/tools/preview_text_workspace">Try the text preview ↗</a></div>`}<p id="workspace-status" class="status" role="status" aria-live="polite"></p><div id="workspace-error" class="error" role="alert" hidden></div><section id="result-panel" hidden><p class="eyebrow">03 / YOUR RESULT ${badge('Sample · demo')}</p><pre id="result-output"></pre><a id="result-download" class="button secondary">Download private sample ↧</a><p class="fine">Available only in your current local session.</p></section></div><aside class="tool-info"><h2>Before you begin</h2><dl><dt>Input</dt><dd>${esc(tool.inputType)}</dd><dt>Output</dt><dd>${esc(tool.outputType)}</dd><dt>Price</dt><dd>${esc(tool.price.label)}</dd></dl><h3>Know the limits</h3><ul>${tool.limitations.map(value => `<li>${esc(value)}</li>`).join('')}</ul><h3>Privacy & retention</h3><p>${esc(tool.privacy)}</p><details><summary>Sample output</summary><pre>${esc(JSON.stringify(tool.exampleOutput, null, 2))}</pre></details></aside></section>`);
  });
  router.get('/pricing', (req, res) => send(req, res, 'Pricing', `${intro('TRANSPARENT FROM THE START', 'Know before you run.', 'Every task starts with a quote. The current local preview uses demo credits and never takes real money.')}<section class="pricing-layout"><div class="price-block">${badge('Local demo')}<h2>A small trial.<br>A complete workflow.</h2><p class="price">$0 <span>real charge</span></p><p>One demo credit per successful text sample. Your server-confirmed balance appears in your workspace.</p><a class="button" href="/tools/preview_text_workspace">Try the local sample ↗</a></div><div class="prose"><h2>How demo credits work</h2><p>Start a local demo session, review a quote and explicitly confirm it. A credit is reserved before execution and captured when the sample succeeds. Failed runs release the reservation.</p><p>Demo credits have no monetary value and cannot be purchased. The session, credits, jobs and results expire exactly 30 minutes after session creation, or sooner on logout, deletion or server restart.</p><h3>Real pricing comes later</h3><p>Commercial prices, credit conversion, refunds and receipt policies are not available yet. Checkout is disabled while authentication, durable storage and verified payment handling are prepared.</p><a class="text-link" href="/account/credits">See your demo balance →</a></div></section>`));
  router.get('/account/:section', (req, res, next) => {
    const section = req.params.section; if (!['jobs', 'credits', 'settings'].includes(section)) return next();
    const title = { jobs: 'Your recent work.', credits: 'A clear account of credits.', settings: 'Your session, your control.' }[section];
    send(req, res, `Workspace ${section}`, `${intro('YOUR LOCAL WORKSPACE · DEMO', title, 'A temporary local session. No real account, purchases or cloud storage.')}<div class="account-layout"><nav class="account-nav" aria-label="Workspace"><a href="/account/jobs" ${section === 'jobs' ? 'aria-current="page"' : ''}>Job history</a><a href="/account/credits" ${section === 'credits' ? 'aria-current="page"' : ''}>Demo credits</a><a href="/account/settings" ${section === 'settings' ? 'aria-current="page"' : ''}>Session settings</a></nav><section class="account-content" data-account="${section}"><div id="session-summary" class="session-summary"></div><button class="button" id="start-session" type="button">Start local demo session →</button><p id="account-status" role="status" aria-live="polite"></p><div id="account-error" class="error" role="alert" hidden></div><div id="account-data"></div>${section === 'settings' ? `<div id="settings-controls" hidden><h2>Keep or clear your data</h2><p>Export contains your current demo jobs and credit ledger. Logout or deletion immediately invalidates access to jobs and downloads.</p><div class="actions"><a class="button secondary" href="/api/human/export">Export demo data ↧</a><button class="button secondary" id="logout-button">Log out</button></div><details class="delete-section"><summary>Delete local demo session</summary><p>This permanently removes your current in-memory session and its results.</p><label class="confirm"><input id="delete-confirm" type="checkbox"> I understand my demo data will be deleted.</label><button class="button danger" id="delete-button" disabled>Delete session</button></details></div>` : ''}</section></div>`);
  });
  router.get('/developers', (req, res) => send(req, res, 'Developers', `${intro('BUILT TO BE CALLABLE', 'Useful to people.<br>Open to integration.', 'Browser workspaces and agents share a capability registry. Inspect the actual public interfaces and schemas before integrating.')}<section class="prose wide"><h2>Start with discovery</h2><p>The existing gateway exposes a versioned capability catalog, HTTP execution and MCP discovery. Private placeholders remain excluded from public discovery.</p><div class="endpoint"><code>GET /tools</code><a href="/tools?format=json">Machine catalog ↗</a></div><p>Request <code>Accept: application/json</code> for the machine catalog. Browser navigation opens the human catalog.</p><pre>curl -H 'Accept: application/json' http://127.0.0.1:4021/tools</pre><h2>Human workspace schema</h2><p>The browser uses the local-only <code>/api/human</code> interface. It requires a session cookie, same-origin requests and a CSRF token for mutations. Quote confirmation is mandatory.</p><div class="endpoint"><code>GET /api/human/catalog</code><a href="/api/human/catalog">Inspect manifest schemas ↗</a></div><p>Local demo execution uses a separate preview registry and does not imply a commercially ready capability. Use the repository README for the configured gateway HTTP, MCP and x402 setup.</p><h3>Integration readiness</h3><p>Production authentication, distributed credit storage, private artifact storage and Stripe test checkout are not connected. Live payments are disabled.</p></section>`));
  router.get('/help', (req, res) => send(req, res, 'Help', `${intro('A LITTLE CLARITY', 'Make yourself at home.', 'The local preview lets you explore the complete workspace flow without a wallet or a purchase.')}<section class="prose wide"><h2>What works today?</h2><p>Text workspace counts words and characters and returns a short excerpt. It is a local sample, with no AI analysis or rewriting. Document and web page workspaces are future concepts and cannot run.</p><h2>How do I start?</h2><p>Open Text workspace, enter up to 4,000 characters, review the exact demo quote and confirm it. Your result appears on the page, with a private JSON download and a job-history entry.</p><h2>Where does my data go?</h2><p>The sample runs in server memory. No provider receives it. Your session and all associated data expire 30 minutes after creation, on logout or deletion, or when the server restarts. Do not use confidential information.</p><h2>Something did not finish?</h2><p>Read the error next to your form. Expired quotes need a new quote. An expired session needs a new local session. Failed jobs release the reserved credit. If the local server is offline, restart it and reload the page.</p><h2>Need support?</h2><p>Report the visible error and trace ID to the person running this preview. Do not include confidential input.</p><a class="button" href="/tools/preview_text_workspace">Open text workspace ↗</a></section>`));
  router.get('/legal/:document', (req, res, next) => {
    const doc = req.params.document; if (!['privacy', 'terms'].includes(doc)) return next();
    const title = doc === 'privacy' ? 'Privacy' : 'Terms';
    send(req, res, `${title} draft`, `${intro('DRAFT · PENDING REVIEW', `${title}, plainly stated.`, 'These notes describe this local preview. They are not final commercial legal terms.')}<section class="prose wide">${doc === 'privacy' ? '<h2>Local and temporary</h2><p>Text inputs, results and credit records live in server memory, associated with an opaque HTTP-only demo cookie. A CSRF token protects changes. No provider or AI service receives sample text.</p><h2>Retention and access</h2><p>The session expires 30 minutes after creation. Logout, deletion and server restart remove access earlier. Artifact downloads require the same session. Export or delete the current session in settings.</p><h2>Your choice</h2><p>Do not enter confidential data. Files are not accepted and URLs are not fetched. Real account and payment integrations are not configured.</p>' : '<h2>A preview, with limits</h2><p>The text sample demonstrates the workspace interface. It is not a commercial analysis or rewriting service. Future workspace listings cannot execute.</p><h2>No purchase</h2><p>Demo credits have no monetary value. No checkout or live payments are enabled. No commercial refund or credit policy is offered in this preview.</p><h2>Temporary availability</h2><p>Results and demo records are temporary and may disappear on session expiry or server restart. Download a sample within your session if you want to retain it.</p>'}<p>Updated 3 October 2026. Final terms and privacy disclosures require review before commercial release.</p><a class="text-link" href="/account/settings">Manage your local session →</a></section>`);
  });
  return router;
}
